### ISSUE TITLE
Plugin won't load

### ISSUE THREAD

**Issue by Ymerejliaf** [MarkehMe/FactionsPlus#184]
Hi,
I'm assuming that this error is something to do with the version of java or bukkit, but I'm not sure. At any rate, here's the error I get. I appreciate any help given in advance.

[17:17:53] [Server thread/WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: me/markeh/factionsplus/FactionsPlus : Unsupported major.minor version 52.0
[17:17:53] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135)
[17:17:53] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329)
[17:17:53] [Server thread/WARN]: at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:275)
[17:17:53] [Server thread/WARN]: at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114)
[17:17:53] [Server thread/WARN]: at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:104)
[17:17:53] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[17:17:53] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[17:17:53] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[17:17:53] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
[17:17:53] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
[17:17:53] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[17:17:53] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[17:17:53] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[17:17:53] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:722)
[17:17:53] [Server thread/WARN]: Caused by: java.lang.UnsupportedClassVersionError: me/markeh/factionsplus/FactionsPlus : Unsupported major.minor version 52.0
[17:17:53] [Server thread/WARN]: at java.lang.ClassLoader.defineClass1(Native Method)
[17:17:53] [Server thread/WARN]: at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
[17:17:53] [Server thread/WARN]: at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[17:17:53] [Server thread/WARN]: at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
[17:17:53] [Server thread/WARN]: at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
[17:17:53] [Server thread/WARN]: at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[17:17:53] [Server thread/WARN]: at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[17:17:53] [Server thread/WARN]: at java.security.AccessController.doPrivileged(Native Method)
[17:17:53] [Server thread/WARN]: at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[17:17:53] [Server thread/WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
[17:17:53] [Server thread/WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[17:17:53] [Server thread/WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
[17:17:53] [Server thread/WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
[17:17:53] [Server thread/WARN]: at java.lang.Class.forName0(Native Method)
[17:17:53] [Server thread/WARN]: at java.lang.Class.forName(Class.java:264)
[17:17:53] [Server thread/WARN]: at org.bukkit.plugin.java.PluginClassLoader.

**Comment by MarkehMe** [comment]
Please update to Java 8 :-)
