### ISSUE TITLE
NPE with FPlayer.get()

### ISSUE THREAD

**Issue by SirFaizdat** [MarkehMe/FactionsPlus#191]
I have been receiving this error with numerous commands (I ran /f announce for this one though). 

Stack trace:
```
10.01 21:56:11 [Server] INFO [FactionsPlus] [Error] Oh no, an internal error has occurred! :-(
10.01 21:56:11 [Server] WARN java.lang.NullPointerException
10.01 21:56:11 [Server] WARN at me.markeh.factionsframework.objs.FPlayer.get(FPlayer.java:22)
10.01 21:56:11 [Server] WARN at me.markeh.factionsframework.faction.Faction.msg(Faction.java:61)
10.01 21:56:11 [Server] WARN at me.markeh.factionsplus.commands.CmdAnnounce.run(CmdAnnounce.java:49)
```

**Comment by MarkehMe** [comment]
Please provide the entire stack trace and provide your version of Factions and/or MassiveCore!

**Comment by MarkehMe** [comment]
Please try beta 4 and let me know if there is an issue.
