### ISSUE TITLE
[Error] Oh no, an internal error has occurred! :-(

### ISSUE THREAD

**Issue by MrEvilChaos** [MarkehMe/FactionsPlus#193]
http://pastebin.com/c7bSxEV1

**Comment by MarkehMe** [comment]
I haven't tested with 2.8.3 but if you would like to test this build and see if it works that would be awesome. 

[FactionsPlus.jar.zip](https://github.com/MarkehMe/FactionsPlus/files/98611/FactionsPlus.jar.zip)

**Comment by MrEvilChaos** [comment]
Sorry, but still an error

----------------------------------------
Error Log started on Wed Jan 20 22:35:02 EST 2016
----------------------------------------
Server Version: git-Spigot-db6de12-18fbb24 (MC: 1.8.8)
FactionsPlus Version: 2.0.0-beta3
Factions Version: 2.8.3
MassiveCore Version: 2.8.3
----------------------------------------
Error:com.massivecraft.factions.cmd.CmdFactions.removeSubCommand(Lcom/massivecraft/massivecore/cmd/MassiveCommand;)I
----------------------------------------
java.lang.NoSuchMethodError: com.massivecraft.factions.cmd.CmdFactions.removeSubCommand(Lcom/massivecraft/massivecore/cmd/MassiveCommand;)I
	at me.markeh.factionsframework.command.versions.FactionsCommandManager2X.removeCommand(FactionsCommandManager2X.java:42)
	at me.markeh.factionsplus.commands.CommandManager.remove(CommandManager.java:63)
	at me.markeh.factionsplus.FactionsPlus.disable(FactionsPlus.java:140)
	at me.markeh.factionsplus.FactionsPlusPlugin.onDisable(FactionsPlusPlugin.java:56)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323)
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364)
	at com.massivecraft.massivelag.inject.event.MassiveLagPluginLoader.disablePlugin(MassiveLagPluginLoader.java:221)
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424)
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.disablePlugins(CraftServer.java:336)
	at net.minecraft.server.v1_8_R3.MinecraftServer.stop(MinecraftServer.java:460)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:593)
	at java.lang.Thread.run(Thread.java:745)
----------------------------------------

**Comment by MarkehMe** [comment]
Just tested it and worked it out.. try this out.

[FactionsPlus.jar.zip](https://github.com/MarkehMe/FactionsPlus/files/98624/FactionsPlus.jar.zip)

**Comment by MrEvilChaos** [comment]
Yes working like a charm!

**Comment by MarkehMe** [comment]
Great. 

This is included in the released beta 4 which you can grab from here: http://dev.bukkit.org/bukkit-plugins/factionsplus/files/54-factions-plus-v2-0-0-beta4/
