### ISSUE TITLE
Factions Command errors with 2.8.7Beta

### ISSUE THREAD

**Issue by rockmanvnx6** [MarkehMe/FactionsPlus#199]
this is my error.log : http://pastebin.com/RbhTnS7Q
my bukkit version is 1.8.8

**Comment by SirFaizdat** [comment]
I'm also having this problem.

**Comment by MarkehMe** [comment]
Hi! Thanks for letting me know. Factions 2.8.7Beta has not been properly tested yet, however I quickly put this together and it should fix support for it. 

[FactionsPlus.jar.zip](https://github.com/MarkehMe/FactionsPlus/files/181168/FactionsPlus.jar.zip)

Please let me know if this works for you.

**Comment by SirFaizdat** [comment]
I'm getting this error now. Note that the stack trace is backwards (so it starts at the bottom).
```
20.03 01:09:29 [Server] WARN ... 6 more
20.03 01:09:29 [Server] WARN at java.lang.ClassLoader.loadClass(Unknown Source)
20.03 01:09:29 [Server] WARN at java.lang.ClassLoader.loadClass(Unknown Source)
20.03 01:09:29 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
20.03 01:09:29 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
20.03 01:09:29 [Server] WARN at java.net.URLClassLoader.findClass(Unknown Source)
20.03 01:09:29 [Server] WARN Caused by: java.lang.ClassNotFoundException: me.markeh.factionsplus.listeners.CoreListener
20.03 01:09:29 [Server] WARN at java.util.TimerThread.run(Unknown Source)
20.03 01:09:29 [Server] WARN at java.util.TimerThread.mainLoop(Unknown Source)
20.03 01:09:29 [Server] WARN at me.markeh.factionsplus.conf.obj.FileWatchTask.run(FileWatchTask.java:26)
20.03 01:09:29 [Server] WARN at me.markeh.factionsplus.conf.obj.Configuration$1.onChange(Configuration.java:200)
20.03 01:09:29 [Server] WARN at me.markeh.factionsplus.conf.Config.postUpdatePing(Config.java:161)
20.03 01:09:29 [Server] WARN at me.markeh.factionsplus.FactionsPlus.manageListeners(FactionsPlus.java:209)
20.03 01:09:29 [Server] WARN java.lang.NoClassDefFoundError: me/markeh/factionsplus/listeners/CoreListener
20.03 01:09:29 [Server] WARN Exception in thread "Timer-119" 
```

**Comment by MarkehMe** [comment]
Did you reload or restart?

**Comment by SirFaizdat** [comment]
I restarted the server, and there are no errors, but it doesn't seem that FactionPlus' commands are registering. When typing "/f warps" or "/f rules", it just says that the subcommand couldn't be found. Here is my FactionsPlus folder. 

[FactionsPlus.zip](https://github.com/MarkehMe/FactionsPlus/files/181175/FactionsPlus.zip)

**Comment by rockmanvnx6** [comment]
`nt to FactionsPlus
[13:43:25 INFO]: [FactionsPlus] [Error] Oh no, an internal error has occurred! :                                               -(
[13:43:25 WARN]: java.lang.NoSuchMethodError: me.markeh.factionsframework.comman                                               d.versions.FactionsCommand2_XWrapper.setHelp([Ljava/lang/String;)V
[13:43:25 WARN]:        at me.markeh.factionsframework.command.versions.Factions                                               Command2_XWrapper.<init>(FactionsCommand2_XWrapper.java:33)
[13:43:25 WARN]:        at me.markeh.factionsframework.command.versions.Factions                                               CommandManager2_X.addCommand(FactionsCommandManager2_X.java:25)
[13:43:25 WARN]:        at me.markeh.factionsplus.commands.CommandManager.enable                                               Cmd(CommandManager.java:73)
[13:43:25 WARN]:        at me.markeh.factionsplus.commands.CommandManager.add(Co                                               mmandManager.java:44)
[13:43:25 WARN]:        at me.markeh.factionsplus.FactionsPlus.enable(FactionsPl                                               us.java:110)
[13:43:25 WARN]:        at me.markeh.factionsplus.FactionsPlusPlugin.onEnable(Fa                                               ctionsPlusPlugin.java:42)
[13:43:25 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlug                                               in.java:321)
[13:43:25 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(                                               JavaPluginLoader.java:340)
[13:43:25 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(Si                                               mplePluginManager.java:405)
[13:43:25 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin                                               (CraftServer.java:357)
[13:43:25 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlug                                               ins(CraftServer.java:317)
[13:43:25 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(Minecr                                               aftServer.java:414)
[13:43:25 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(Minecr                                               aftServer.java:378)
[13:43:25 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(Minecr                                               aftServer.java:333)
[13:43:25 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(Ded                                               icatedServer.java:263)
[13:43:25 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(Mine                                               craftServer.java:525)
[13:43:25 WARN]:        at java.lang.Thread.run(Unknown Source)
[13:43:25 INFO]: [FactionsPlus] [Error] It has been saved to plugins\FactionsPlu                                               s\logs\1458506605237.errorlog
[13:43:25 INFO]: [FactionsPlus] [Error] Please upload to pastebin.com and includ                                               e in any error reports.
[13:43:25 INFO]: [bChatManager] Enabling bChatManager v3.1.5
[13:43:25 INFO]: [bChatManager] Enabled
[13:43:25 INFO]: Server permissions file permissions.yml is empty, ignoring it
[13:43:25 INFO]: Done (8.046s)! For help, type "help" or "?"
[13:43:25 INFO]: [Jobs] [Jobs] Successfully linked with Vault.
[13:43:25 INFO]: [Buycraft] Authenticated with the specified Secret key.
[13:43:25 INFO]: [Buycraft] Plugin is now ready to be used.
[13:43:25 INFO]: [Vault] Checking for Updates ...
[13:43:25 INFO]: [Vault] No new version available
[13:43:25 INFO]: [Buycraft] Loaded 1 package(s) into the cache.
[13:43:27 INFO]: [ProtocolLib] The updater found an update: 3.7.0-BETA (Running                                                3.6.6-SNAPSHOT-b224). Download at https://www.spigotmc.org/resources/protocollib                                               .1997/
[13:43:27 INFO]: [VanishNoPacket] Error: Could not check if plugin was up to dat                                               e. Will try later
[13:43:27 INFO]: [VanishNoPacket] Exception message: Server returned HTTP respon                                               se code: 403 for URL: https://api.curseforge.com/servermods/files?projectIds=309   `


i downloaded your file and replaced it with my faction plus folder, this is what i got.

**Comment by MarkehMe** [comment]
Fixed. 

[FactionsPlus.jar.zip](https://github.com/MarkehMe/FactionsPlus/files/181196/FactionsPlus.jar.zip)
