### ISSUE TITLE
Plugin is not loading 

### ISSUE THREAD

**Issue by TheCobalt** [MarkehMe/FactionsPlus#205]
Here is the main line from my Console:
[18:53:24] [Server thread/ERROR]: Could not load 'plugins\FactionsPlus.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: me/markeh/factionsplus/FactionsPlus : Unsupported major.minor version 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot.jar:git-Spigot-129f87a-6bf25cd]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-129f87a-6bf25cd]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-129f87a-6bf25cd]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugins(CraftServer.java:296) [spigot.jar:git-Spigot-129f87a-6bf25cd]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:201) [spigot.jar:git-Spigot-129f87a-6bf25cd]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot.jar:git-Spigot-129f87a-6bf25cd]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0]
Caused by: java.lang.UnsupportedClassVersionError: me/markeh/factionsplus/FactionsPlus : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.7.0]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.7.0]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.7.0]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.7.0]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-129f87a-6bf25cd]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-129f87a-6bf25cd]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0]
	at java.lang.Class.forName(Unknown Source) ~[?:1.7.0]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-129f87a-6bf25cd]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot.jar:git-Spigot-129f87a-6bf25cd]
	... 6 more

**Comment by DraksterAU** [comment]
Update your Java.

**Comment by TheCobalt** [comment]
I actually use a host, how could I update the server java?

**Comment by DraksterAU** [comment]
You'll have to ask them... Or get a better host..... Java 7 is out of date by at least 2 years now

**Comment by DraksterAU** [comment]
Mark might be willing to compile FP for Java 7 - or you could try - it isn't hard :)

**Comment by TheCobalt** [comment]
I will try thanks!

**Comment by DraksterAU** [comment]
If you haven't fixed this in the Next 8 hrs I'll compile you a copy :)

**Comment by TheCobalt** [comment]
Thank you very much! It's been confusing so if you have the time then I would love that!

**Comment by DraksterAU** [comment]
@TheCobalt Sorry man.. I just realised FP depends on FactionsUUID for compilation.

Needs to be Mark.. I'm not buying it for this sorry :D

**Comment by MarkehMe** [comment]
I actually use some Java 8 methods! But I will see what I can do:)

**Comment by TheCobalt** [comment]
Okay thank you for your response. I understand how you wouldn't want to pay that ridiculous price for FactionsUUID

**Comment by DraksterAU** [comment]
Haha no worries.

I would if I was going to use it more than once

**Comment by MarkehMe** [comment]
(P.s. I didn't buy FactionsUUID, I compiled it from https://github.com/drtshock/Factions) 

There are way too many Java 8 methods used - sorry, I can't compile it with Java 7. 😞

**Comment by DraksterAU** [comment]
Oh cool!
